spring:
   application:
    name: otc-notfiy-server
   thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5   
   cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled:  true
        serviceId:  notfiy-server
    bus:
      enabled: true
      trace:
        enabled: true
   client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
   datasource:
    url: jdbc:mysql://47.52.108.99:3306/msg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: user_gw
    password: teus2019gw
    driverClassName: com.mysql.jdbc.Driver
    hikari:
       connection-test-query: SELECT 1 FROM DUAL
       connection-timeout: 600000
       maximum-pool-size: 500
       max-lifetime: 1800000
       minimum-idle: 20
       validation-timeout: 3000
       idle-timeout: 60000
       connection-init-sql: SET NAMES utf8mb4
   redis:
    port: 6379
    host: 127.0.0.1
    timeout : 5000
    pool :
        max-idle : 100
        min-idle : 10
        max-active : 1000
        max-wait : -1
feign.hystrix.enabled: true  
logging:
  level:
      otc.*: debug  