eureka : 
  client:
    serviceUrl:
      defaultZone:  http://47.52.108.99:8761/eureka/
spring:
   application:
    name: otc-queue-apk-server
   thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5   
   cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled:  true
        serviceId:  queue-apk-server
    bus:
      enabled: true
      trace:
        enabled: true
   redis:
    port: 6379
    host: 127.0.0.1
    timeout : 5000
    pool :
        max-idle : 100
        min-idle : 10
        max-active : 1000
        max-wait : -1
feign.hystrix.enabled: true  
logging:
  level:
      otc.*: debug   