spring:
  datasource:
    url: jdbc:mysql://rm-3nss9b6z93e4rk299.mysql.rds.aliyuncs.com:3306/otc_alipay?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: kent_admin
    password: L!f2e#e_h3CNgVD
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
  redis:
    port: 6379
    host: r-3nsnbeyh1ym8vjo2vf.redis.rds.aliyuncs.com
    timeout: 5000
    password: kentredis:Bffdasdsdada9ijnasd6
    pool:
      max-idle: 200
      min-idle: 10
      max-active: 1000
      max-wait: -1
#以上为线上发布配置文件