eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: otc-zuul-server
zuul:
  strip-prefix: false
  routes:
    api-a:
      path: /api-alipay/**
      serviceId: otc-alipay-server