eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: otc-zuul-server
zuul:
  strip-prefix: false
  routes:
    api-a:
      path: /api-alipay/**
      serviceId: otc-alipay-server
  host:
    maxTotalConnections: 6000000
    maxPerRouteConnections: 600000
  max:
    host:
      connections: 1000000
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    c4i-store:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
            ribbon:
              ReadTimeout: 600000
              ConnectTimeout: 600000