eureka : 
  client:
    serviceUrl:
      defaultZone:  http://120.78.197.211:8761/eureka/
  instance:
    # 是否使用ip注册
    prefer-ip-address : true
    # ${spring.cloud.client.ip-address}:${server.port}  局域网这样配置
    #  本地调试则要直接写死ip 【这个ip为注册时候的 调用ip】
    instance-id : 47.52.108.99:${server.port}
    # 注册ip地址 公网注册地址 47.52.108.99
    ip-address :  47.52.108.99
    # 注册ip端口
    non-secure-port : ${server.port}
    hostname : 47.52.108.99:${server.port}
   # status-page-url : c.biancheng.net
spring:
   application:
    name: otc-task-config-server
   thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5   
   cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled:  true
        serviceId:  task-config-server
    bus:
      enabled: true
      trace:
        enabled: true
feign.hystrix.enabled: true  
logging:
  level:
      otc.*: debug   