eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    # 是否使用ip注册
    prefer-ip-address: true
    # ${spring.cloud.client.ip-address}:${server.port}  局域网这样配置
    #  本地调试则要直接写死ip 【这个ip为注册时候的 调用ip】  47.52.108.99
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 注册ip地址http://182.16.89.146
    ip-address: ${spring.cloud.client.ip-address}
    # 注册ip端口
    non-secure-port: ${server.port}
    hostname: ${spring.cloud.client.ip-address}:${server.port}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: otc-task-config-server
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        serviceId: task-config-server
    bus:
      enabled: true
      trace:
        enabled: true
feign.hystrix.enabled: true  
logging:
  level:
      otc.*: debug   