eureka : 
  client:
    serviceUrl:
      defaultZone:  http://47.52.108.99:8761/eureka/
  instance:
    prefer-ip-address : true
    instance-id : ${spring.cloud.client.ipAddress}:${server.port}
spring:
   application:
    name: otc-task-config-server
   thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5   
   cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled:  true
        serviceId:  task-config-server
    bus:
      enabled: true
      trace:
        enabled: true
feign.hystrix.enabled: true  
logging:
  level:
      otc.*: debug   