spring:
  application:
    name: otc-admin-server
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
#断路器开启
feign.hystrix.enabled: true
logging:
  level:
     admin.*: debug   