eureka : 
  client:
    serviceUrl:
      defaultZone:  http://47.52.108.99:8761/eureka/
  instance:
    prefer-ip-address : true
    instance-id : ${spring.cloud.client.ip-address}:${server.port}
    hostname : ${spring.cloud.client.ip-address}
spring:
   application:
    name: otc-dealpay-server
   thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5   
   cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled:  true
        serviceId:  dealpay-server
    bus:
      enabled: true
      trace:
        enabled: true
   datasource:
    url: jdbc:mysql://47.52.108.99:3306/otc_dealpay?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: user_gw
    password: teus2019gw
    driverClassName: com.mysql.jdbc.Driver
    hikari:
       connection-test-query: SELECT 1 FROM DUAL
       connection-timeout: 600000
       maximum-pool-size: 500
       max-lifetime: 1800000
       minimum-idle: 20
       validation-timeout: 3000
       idle-timeout: 60000
       connection-init-sql: SET NAMES utf8mb4
   redis:
    port: 6379
    host: 127.0.0.1
    timeout: 5000
    pool:
        max-idle : 100
        min-idle : 10
        max-active : 1000
        max-wait : -1
   http :
      encoding :
         force : true
         charset : UTF-8
         enabled : true
   servlet :
     multipart : 
        max-file-size : 100MB
        max-request-size : 100MB
   session:
    store-type: redis
    timeout: 7200s
#断路器开启
feign.hystrix.enabled: true  
logging:
  level:
      deal.*: debug   